language: java
dist: xenial

services:
  - docker

branches:
  only:
    - master

install:
  - set -e
  - nohup docker pull localstack/localstack > /dev/null &
  - nohup docker pull lambci/lambda:java8 > /dev/null &

script:
  - set -e
  - make test

notifications:
  email: false
